modLoader="javafml"
loaderVersion="[37,)"
license="GPLv3"
[[mods]]
modId="konkrete"
version="1.3.0"
displayName="Konkrete"
logoFile="konkrete.png"
authors="Keksuccino"
description='''

COPYRIGHT:

Konkrete Copyright © 2020-2021 Keksuccino.
Konkrete is licensed under GPLv3.

Open Imaging Copyright © 2014 Dhyan Blum.
Open Imaging is licensed under Apache-2.0.

'''
